version: 1.0.{build}
clone_depth: 50

# Set up environment variables for build info
environment:
  CUBERITE_BUILD_SERIES_NAME: AppVeyor
  CUBERITE_BUILD_ID: "%APPVEYOR_BUILD_NUMBER%"
  CUBERITE_BUILD_DATETIME: "%APPVEYOR_REPO_COMMIT_TIMESTAMP%"

  matrix:
  - job_name: Android
    configuration: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    CUBERITE_EXECUTABLE: cuberite

  - job_name: Windows-x86
    configuration: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CUBERITE_EXECUTABLE: cuberite

  - job_name: Windows-x64
    configuration: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CUBERITE_EXECUTABLE: cuberite

install:
- echo %TIME%
- git submodule update --init

for:
##############################
# Windows 64-bit debug build #
##############################
-
  matrix:
    only:
      - job_name: Windows-x64-debug

  before_build:
  - if not exist Debug-x64 mkdir Debug-x64
  - cd Debug-x64
  - echo %TIME%
  - cmake -G "Visual Studio 14 2015 Win64" -DSELF_TEST=1 -DBUILD_TOOLS=1 ..
  - echo %TIME%
  - cd ..

  build:
    project: Debug-x64\Cuberite.sln
    parallel: true
    verbosity: minimal

################################
# Android release build #
################################
-
  matrix:
    only:
      - job_name: Android

  install:
  - git submodule update --init
  - curl -LO https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -o android-ndk*
  - NDK="android-ndk-r13b/" CMAKE="/usr/bin/cmake" android/compile.sh all

################################
# Windows 32-bit release build #
################################
-
  matrix:
    only:
      - job_name: Windows-x86

  before_build:
  - if not exist Release-x86 mkdir Release-x86
  - cd Release-x86
  - echo %TIME%
  - cmake -G "Visual Studio 14 2015" ..
  - echo %TIME%
  - cd ..

  build:
    project: Release-x86\Cuberite.sln
    parallel: true
    verbosity: minimal

################################
# Windows 64-bit release build #
################################
-
  matrix:
    only:
      - job_name: Windows-x64

  before_build:
  - if not exist Release-x64 mkdir Release-x64
  - cd Release-x64
  - echo %TIME%
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - echo %TIME%
  - cd ..

  build:
    project: Release-x64\Cuberite.sln
    parallel: true
    verbosity: minimal

cache:
  - Debug-x64
  - Release-x86
  - Release-x64

after_build:
- cmd: cd Install
- cmd: echo Cuberite %APPVEYOR_JOB_NAME%-#%APPVEYOR_BUILD_NUMBER%  1>..\Server\buildinfo.txt  
- cmd: 7z a -tzip -y ../Cuberite.zip -scsWIN -i@Zip2008.list -xr!*.git*
- cmd: cd ..
- cmd: 7z a -tzip -y PDBs.zip -scsWIN -i@Install/Zip2008_PDBs.list -xr!*.git*
- cmd: cd Server\plugins
- cmd: git clone https://github.com/madmaxoft/ManualApiDump
- cmd: cd ..
- cmd: echo load ManualApiDump  1>cmds.txt
- cmd: echo manualapi  1>>cmds.txt
- cmd: echo load APIDump  1>>cmds.txt
- cmd: echo api  1>>cmds.txt
- cmd: echo stop  1>>cmds.txt
- cmd: "%CUBERITE_EXECUTABLE% --port 32767  0<cmds.txt"
- cmd: cd ..
- cmd: cd src/Bindings/docs
- cmd: 7z a -tzip -y ../../../AutoAPI.zip -scsWIN "*.lua" -x!_raw.lua
- cmd: cd ..\..\..\Server
- cmd: 7z a -tzip -y ../ManualAPI.zip -scsWIN "ManualAPI.lua"

artifacts:
  - path: Cuberite.zip
    name: Cuberite

  - path: PDBs.zip
    name: PDBs

  - path: AutoAPI.zip
    name: AutoAPI

  - path: ManualAPI.zip
    name: ManualAPI

  - path: Server\.luacheckrc
    name: .luacheckrc

  - path: server.zip
    name: server
