name: MacOS CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1.2.0
      with:
        submodules: recursive

    - run: mkdir Release
    - name: cmake
      run: cmake .. -DNO_NATIVE_OPTIMIZATION=1 -DCMAKE_BUILD_TYPE=RELEASE
      working-directory: Release

    #- name: make
    #  run: make -j`nproc`
    #  working-directory: Release
    #  env: 
    #    CUBERITE_BUILD_SERIES_NAME: MacOS
    #    CUBERITE_BUILD_ID: $GITHUB_RUN_NUMBER
    #    CUBERITE_BUILD_DATETIME: $TIME

    - run: echo Cuberite $CUBERITE_BUILD_SERIES_NAME-$CUBERITE_BUILD_ID > buildinfo.txt
      working-directory: Release/Server
      env: 
        CUBERITE_BUILD_SERIES_NAME: MacOS
        CUBERITE_BUILD_ID: $GITHUB_RUN_NUMBER
        CUBERITE_BUILD_DATETIME: $TIME

    - name: cleanup
      run: rm !($(tr \\n \| < Install/UnixExecutables.list ))
      working-directory: Release/Server

    - uses: actions/upload-artifact@v1
      with:
        name: Server
        path: Release/Server/
