name: Tests
on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Release, Debug]
        c_compiler: [gcc, clang]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++
    env:
      CI_CUBERITE_BUILD_TYPE: ${{ matrix.build_type }}
      CI_JOB_NUMBER: ${{ github.run_number }}
      CC: ${{ matrix.c_compiler }}
      CXX: ${{ matrix.cpp_compiler }}

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'

    - name: Build and run tests
      run: ./cibuild.sh

    - name: Upload artifact
      if: matrix.build_type == 'Release' && matrix.c_compiler == 'gcc'
      uses: actions/upload-artifact@v7
      with:
        path: gcc_Release/Server/.luacheckrc
        archive: false
